# Basic
title: æ›¹äºšå¼º
subtitle: è¢–é‡Œä¹¾å¤
description: å±±ä¸åœ¨é«˜ï¼Œæœ‰ä»™åˆ™åã€‚æ°´ä¸åœ¨æ·±ï¼Œæœ‰é¾™åˆ™çµã€‚æ–¯æ˜¯é™‹å®¤ï¼ŒæƒŸå¾å¾·é¦¨ã€‚
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ArthurCao
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS & ç”Ÿæ´»
url: "arthurcao.com"

# Comment
comment:
    netCloudTie: 2a493b749dcc4c26a3793d480641c20c

# Social
social:
    weibo: ArthurCaoV587 
    github: honeycao
    # twitter: 
    mail: arthurcao68@icloud.com

# ç™¾åº¦ç»Ÿè®¡
baidu: 
    id: d1b6174eea5dd40a3ce54a35a57d63f9  
    
# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† 
#  åœ°å€ï¼š https://github.com/honeycao/honeycao.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹

#æ–‡ç« å›ºå®šé“¾æ¥æ ·å¼
permalink: /blog/:title.html

markdown: kramdown


kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge

# Format
highlighter: rouge

# only supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: clear

# The blog button should not be removed.
blog_button:
    title: ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: å½’æ¡£, description: archive, url: '/navigationItem/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/navigationItem/tags'} 
    - {title: èµ„æº, description: resources, url: '/navigationItem/resources'}     
    - {title: å…³äº, description: about, url: '/navigationItem/about'}    
    

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"


